#!/bin/sh

## Exit code legend
# -2: Unknown error
# -1: Missing arguments
#  0: Success (chart matches or chart is new/uploaded)
#  1: Chart doesn't match

set -e  ## Exit on error

TMPDIR=$(mktemp -d)
if [ -z "$1" ]; then
    echo "Missing Arguments" >&2
    echo "Usage: $0 <path/to/chart> [--upload]"
    echo "Note: Order is important. If specified `--upload` MUST come after `path/to/chart`"
    exit -1
fi

CHARTDIR=$(realpath "$1")

cd ${TMPDIR}
helm dep up "${CHARTDIR}"
helm package "${CHARTDIR}"

LOCAL_PACKAGE=$(ls *.tgz | head -n1)
LOCAL_COPY="local.${LOCAL_PACKAGE}"
REMOTE_PACKAGE="remote.${LOCAL_PACKAGE}"
mv "${LOCAL_PACKAGE}" "${LOCAL_COPY}"

CHART_NAME=$(echo "${LOCAL_PACKAGE}" | sed -E 's/(.*)-[0-9].*/\1/')
CHART_VERSION=$(echo "${LOCAL_PACKAGE}" | sed -E 's/.*-([0-9][^.]*(\.[0-9]+)*)\.tgz/\1/')

helm registry login ${HELM_REPO_URL} --username "${ECCR_USER}" --password "${ECCR_PASSWORD}"


set +e
PULL_OUTPUT=$(helm pull oci://${HELM_REPO_URL}/${HELM_REPO_CHANNEL}/${CHART_NAME} --version ${CHART_VERSION} --destination .)
PULL_RESULT=$?
set -e

if [ $PULL_RESULT -ne 0 ]; then
    echo "Chart not found on remote" >&2
    if [ "$2" = "--upload" ]; then
        echo "Uploading chart..."
        helm push "${LOCAL_COPY}" "oci://${HELM_REPO_URL}/${HELM_REPO_CHANNEL}"
        echo -e "\nDone."
    fi
    exit 0
fi

if [ ! -f "${LOCAL_PACKAGE}" ]; then
    echo "Pulled chart archive not found!" >&2
    ls -lah
    exit 2
fi

mv "${LOCAL_PACKAGE}" "${REMOTE_PACKAGE}"

mkdir local remote
tar xf "${LOCAL_COPY}" -C local
tar xf "${REMOTE_PACKAGE}" -C remote
for DIR in local remote; do
    rm -f ${DIR}/**/*.lock
done
set +e
diff -r local remote
RESULT=$?
if [ $RESULT -eq 1 ]; then
    echo "Chart contains changes, but the version number has not been updated!" >&2
    exit 1
else
    echo "No changes detected!"
fi
echo "Done."