apiVersion: v1
kind: Service
metadata:
  name: {{ include "gsprestapi.fullname" . }}
  labels:
{{ include "gsprestapi.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "gsprestapi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
