# Default values for gsprestapi.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: "eccr.ecmwf.int/geoglows_api/geoglows_api"
  tag: latest
  pullPolicy: Always

imagePullSecrets:
- name: eccr-ecmwf-int
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.org/mergeable-ingress-type: "master"
    nginx.org/proxy-connect-timeout: 300s
    nginx.org/proxy-read-timeout: 300s
    nginx.org/proxy-send-timeout: 300s

  rootAnnotations:
    nginx.org/mergeable-ingress-type: "minion"

  rateLimitAnnotations:
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/limit-req-rate: "12r/m"
    nginx.org/limit-req-burst: "3" 
    nginx.org/limit-req-key: "${binary_remote_addr}"
    nginx.org/limit-req-zone-size: "10m"
    nginx.org/limit-req-reject-code: "429"

  hosts:
  - host: geoglows.ecmwf.int
    paths:
    - path: /
      pathType: Prefix
      portName: http

  rateLimitedPaths:
    - path: /api/v1/
    - path: /api/Forecast
    - path: /api/HistoricSimulation
    - path: /api/ReturnPeriods
    - path: /api/DailyAverages
    - path: /api/MonthlyAverages
    - path: /api/Available
    - path: /api/GetReachID
    - path: /api/v2/forecast
    - path: /api/v2/hydroviewer
    - path: /api/v2/retrospective
    - path: /api/v2/dailyaverages
    - path: /api/v2/monthlyaverages
    - path: /api/v2/annualaverages
    - path: /api/v2/returnperiods

  rateLimitedPathDetails:
    pathType: Prefix
    portName: http

  tls:
  - hosts:
    - geoglows.ecmwf.int
    secretName: geoglows-tls

resources:
  requests:
    cpu: 1
    memory: 3Gi
  limits:
    memory: 6Gi

nodeSelector: {}
tolerations: []
affinity: {}

persistentVolumes:
  geoglows-data-volume:
    mountPath: /mnt
    claimName: nfs-geoglows-prod-pvc

AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
AWS_LOG_GROUP_NAME: AWS_LOG_GROUP_NAME
AWS_LOG_STREAM_NAME: AWS_LOG_STREAM_NAME
AWS_REGION: AWS_REGION
