# Deploy to Staging Workflow
name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to deploy
        required: true

permissions:
  contents: read
  packages: read

env:
  ECCR_GEOGLOWS_TOKEN: ${{ secrets.ECCR_GEOGLOWS_TOKEN }}

jobs:
  deploy:
    name: Deploy to Staging
    if: startswith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Staging
        run: |
          echo ${{ github.ref_name }}
          curl -X POST -H "Authorization: Bearer $ECCR_GEOGLOWS_TOKEN" -d "bamboo.COMMIT_TAG=${{ github.ref_name }}" https://bamboo.ecmwf.int/rest/api/latest/queue/GEOGLOWS-GSPRES0
